# ----------------------- #
#      Main Configs       #
# ----------------------- #

host: 0.0.0.0
url: https://ukraineaumans.github.io/
title: Association Ukraine Au Mans
email: your-email@domain.com
author: Your Name
description: >
  Association de collaboration humanitaire, culturelle et économique entre les sarthois et les ukrainiens
copyright: 'Copyright &copy; 2022 Association Ukraine Au Mans. All Rights Reserved.'
credits: 'Credits: Theme inspired by <a href="http://jekyllthemes.org/themes/landing-page/">Landing Page</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

